/**
 * (C) Copyright IBM Corp. 2019.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package exampleservicev1

import (
  "github.ibm.com/dustinpopp/ibm-generated-cli-plugin-template/utils"
  "github.com/spf13/cobra"
  "github.com/IBM-Cloud/ibm-cloud-cli-sdk/bluemix/terminal"
  "github.com/IBM/go-sdk-core/core"
)

var ui terminal.UI

// declare the Authenticator for the service
var Authenticator core.Authenticator
var OutputFormat string
var JMESQuery string

// add a function to return the super-command
func GetExampleServiceV1Command() *cobra.Command {
  ui = terminal.NewStdUI()

  // initialize the authenticator
  ServiceAuthenticator, AuthFactoryErr := core.GetAuthenticatorFromEnvironment("example-service-v1")
  utils.HandleError(AuthFactoryErr)

  Authenticator = ServiceAuthenticator

  serviceCommands := []*cobra.Command{
    getListResourcesCommand(),
    getCreateResourceCommand(),
    getGetResourceCommand(),
  }

  exampleServiceCommand := &cobra.Command{
    Use: "example-service-v1 [operation]",
    Short: "Parent command for Example service",
    Long: "No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
  }

  for _, cmd := range serviceCommands {
    exampleServiceCommand.AddCommand(cmd)
  }

  return exampleServiceCommand 
}
